- packages/cli-common/resources/templates/template-workspace/docker-compose.yaml
- packages/engine-s3-plugin/src/S3ConfigProcessor.ts
I have no idea if this will actually work. Untested.
Defaulting S3_BUCKET to project slug seems completely useless. You usually cannot have dynamic s3 buckets.
> s3 prefix defaults to project slug

- packages/cli-common/resources/templates/template-project/admin/index.html
Without the viewport tag the env still working would add extra paddings
> Handle notch

- packages/engine-http/src/transfer/ExportExecutor.ts
`nextval` does not work in readonly transactions
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/319)
> fix(transfer-api): fix sequence export

- .github/actions/extract-version/action.yaml
- .github/workflows/build.yaml
- .github/workflows/publish-canary.yaml
- .github/workflows/publish.yaml
The GitHub Actions workflow gives the following annotation while running the action:
> Node.js 12 actions are deprecated. For more information see: github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12.
You can see more here: https://github.com/actions/setup-node/compare/v2.5.1...v3.0.0
Signed-off-by: Enes <ahmedenesturan@gmail.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/345)
> chore(actions): update to Node16

- packages/cli-common/resources/templates/template-workspace/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/371)
> fix: engine start command migration does not need dot from v1.2

- packages/database/src/client/Pool.ts
- packages/database/tests/cases/unit/pool.test.ts
- add `connection_started_count` metric: "Total number of connection attempts when started."
- handle possible timeouts of connection disposal
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/425)
> database pool improvements

- packages/schema-utils/src/schemaNormalizer.ts
This PR preserves the default configuration for system and content sections of ACL configuration for admin and content_admin roles.
-----
**Migration Guide: Changes to ACL Default Merging**
A minor adjustment has been made to the merging of default ACL configurations. Previously, it was possible to disable import/export for the admin and content_admin roles by overriding the content and system ACL configurations. However, this behavior was found to be undesirable as it often led to accidental disabling of import/export when attempting to modify other configurations.
If you relied on this behavior, you will need to make adjustments. 
For example, the following code snippet unintentionally disabled import/export for the admin role:
```javascript
export const adminRole = …
```
> acl normalization: deep merge content and system

- docker-compose.yaml
- package.json
- packages/cli/src/commands/migrations/MigrationExecuteCommand.ts
This pull request introduces a new feature, the '--until' option, into the 'migration:execute' command. This enhancement offers users improved control over their migration execution process by enabling them to specify a particular migration as an endpoint. 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/448)
> CLI: migrations:execute - add "until" option

- packages/engine-tenant-api/src/model/authorization/AclSchemaAccessNodeFactory.ts
- packages/engine-tenant-api/tests/cases/unit/authorization/membershipAwareAccessNode.test.ts
- packages/schema-utils/src/type-schema/acl.ts
- packages/schema/src/schema/acl.ts
This PR introduces new feature that enhances the Access Control List (ACL) permissions for invites. With this enhancement, users can now have more control over invite-related actions and define separate rules for managing memberships.
Previously, the `TenantPermissions` type had properties `invite` and `unmanagedInvite` to determine whether users could invite others. The `manage` property allowed defining rules for managing memberships, including the ability to invite, remove, or view memberships.
Now, the `invite` and `unmanagedInvite` properties can accept either a simple boolean value or a more detailed rule object. This change enables users to set individual rules for invite actions, distinct from the rules for managing memberships. For example, you can allow users with specific roles …
> Tenant API: better invite permissions

- packages/schema-migrations/src/modifications/columns/CreateColumnModification.ts
- packages/schema-migrations/src/modifications/columns/UpdateColumnDefinitionModification.ts
- packages/schema-migrations/src/modifications/columns/columnUtils.ts
- packages/schema-migrations/tests/cases/integration/createColumn.test.ts
- packages/schema-migrations/tests/cases/integration/updateColumnDefinition.test.ts
This pull request enhances the migration functionality in Contember by introducing the fillValue and copyValue options to the `updateSchemaDefinition` operation. The existing `createColumn` modification already supports these options, and this update extends their usage to the `updateColumnDefinition` operation as well.
The `fillValue`/`copyValue` option allows the migration to fill the modified column with a specific value during the migration run. Unlike the default value used at runtime, the fillValue is exclusively used during the migration process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/451)
> migrations: allow to copyValue/fillValue when updating column definition

- packages/schema-definition/src/index.ts
- packages/schema-definition/src/model/definition/OrderByDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/ManyHasManyDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/ManyHasManyInverseDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/ManyHasOneDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/OneHasManyDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/OneHasOneDefinition.ts
- packages/schema-definition/src/validation/index.ts
- packages/schema-definition/tests/cases/unit/extendEntity.test.ts
- packages/schema-definition/tests/cases/unit/readAclDefinitions.test.ts
- packages/schema-definition/tests/cases/unit/readActions.test.ts
This PR aims to enhance the schema definition API by few things:
- consolidate several schema definition APIs (like SchemaDefinition, AclDefinition etc.) into a single object called "c". 
- allow to pass enums as literal
- all decorators in this new API starts with a first letter upper case
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/430)
> improve schema definition API

- packages/cli-common/src/npm/PackageWorkspace.ts
- packages/cli/src/utils/dockerCompose.ts
The new version mismatch check dit not work well when a contember was inside subfolder of a monorepo. this fixes the issue by scanning parent folders of cwd
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/460)
> cli: fix finding package.json/docker-compose

- packages/engine-http/src/graphql/execution.ts
When a graphql `execute` fails to build an execution context, it returns an object with no `data` key.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/464)
> fix http error code for some graphql validations

- packages/database-migrations/package.json
- packages/database-migrations/src/GroupMigrationsResolver.ts
- packages/database-migrations/src/MigrationsResolver.ts
- packages/database-migrations/src/SnapshotMigrationResolver.ts
- packages/database-migrations/src/helpers.ts
- packages/database-migrations/src/runner.ts
- packages/database-migrations/tests/cases/unit/groupMigrationResolver.test.ts
- packages/database-migrations/tests/cases/unit/snapshotMigrationResolver.test.ts
- packages/engine-system-api/src/migrations/runner.ts
Previously, the migration runner utilized the current time as a prefix for the snapshot migraton. However, a problem arose when a new migration existed in the new engine version but was created before the execution of the snapshot migration in the engine instance. Consequently, the new migration was inadvertently skipped after the engine was upgraded.
This PR resolves the problem by using the timestamp of the latest known migration instead of relying on the current time.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/459)
> internal: fix snapshot migrations time prefix

- packages/engine-tenant-api/src/TenantContainer.ts
- packages/engine-tenant-api/src/model/service/InviteManager.ts
- packages/schema-utils/src/type-schema/settings.ts
- packages/schema/src/schema/settings.ts
This PR introduces the capability to set a custom expiration period for invitations within a specific project. By updating your project's schema, you can now define the validity of project invitations.
```ts
// api/index.ts
import { createSchema } from '@contember/schema-definition'
import * as model from './model'
export default createSchema(model, it => ({
...it,
settings: {
tenant: { inviteExpirationMinutes: 60 * 48 },
},
}))
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/472)
> make invitation expiration configurable

- packages/cli/src/commands/deploy/DeployCommand.ts
- packages/cli/src/utils/admin.ts
- packages/engine-tenant-api/src/model/authorization/PermissionActions.ts
- packages/engine-tenant-api/src/model/authorization/PermissionsFactory.ts
- packages/engine-tenant-api/src/model/authorization/Roles.ts
- packages/engine-tenant-api/src/resolvers/types/IdentityTypeResolver.ts
- packages/engine-tenant-api/src/schema/index.ts
- packages/engine-tenant-api/src/schema/tenant.graphql.ts
This PR brings few features related to a custom "entrypoint" deployment on admin server:
- allow to skip admin / migrations in deploy command
- add canDeployEntrypoint to IdentityGlobalPermissions in tenant API
Related PR: https://github.com/contember/interface/pull/561
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/456)
> CLI: deploy custom frontend, allow deployment without frontend (admin) deploy

- packages/engine-content-api/src/schema/mutations/ConnectOrCreateRelationInputProvider.ts
- packages/engine-content-api/src/schema/mutations/UpdateEntityRelationInputFieldVisitor.ts
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-allowed.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-restricted-create.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-restricted-delete.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-restricted-update.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-basic.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-bug-66.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-custom-primary.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-has-many-reduction.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-new-builder.gql
This update adds missing non-null constraints to fields in various mutation inputs, including `upsert`, `connectOrCreate`, and `update` within has-many relationships. Previously, the absence of these constraints led to Internal errors. This enhancement ensures the correct GraphQL non-null specifications are in place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/480)
> enforce Non-Null constraints on certain mutation inputs

- packages/engine-tenant-api/src/model/mailing/UserMailer.ts
- packages/engine-tenant-api/src/model/service/InviteManager.ts
- packages/engine-tenant-api/src/model/service/PasswordResetManager.ts
So you can use `{{projectSlug}}` in email templates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/481)
> feat(tenant-api): add projectSlug to mail template variables

- packages/cli-common/src/application/Application.ts
- packages/cli-common/src/npm/packageManagers/PackageManagerHelpers.ts
- packages/cli/src/run.ts
- packages/cli/src/utils/checkVersions.ts
- commands like `deploy` and data transfer related commands does not check version mismatch, allowing to not have node_modules installed
- fix workspace package dirs resolving
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/484)
> CLI: skip version check for some commands

- packages/engine-system-api/src/migrations/2023-10-19-173000-fix-unique.ts
- packages/engine-system-api/src/migrations/runner.ts
- packages/engine-system-api/src/model/metadata/ResolvedDatabaseMetadata.ts
- packages/engine-system-api/tests/cases/migrations/2023-10-19-173000-fix-unique.test.ts
- packages/schema-migrations/src/modifications/constraints/index.ts
- packages/schema-utils/src/SchemaDatabaseMetadata.ts
This PR fixes an issue where composed unique constraints weren't removed from the database due to column order mismatches in the schema and in the database.
Changes include:
1. **Column Sorting for Constraints:** Columns are now sorted before operations to prevent mismatches and ensure accurate constraint modifications.
2. **Cleanup Migration:** A migration script is added to identify and remove lingering unique constraints caused by past order discrepancies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/499)
> fix removing unique constraint

- packages/engine-content-api/src/ExecutionContainer.ts
- packages/engine-content-api/src/mapper/select/handlers/FieldsVisitor.ts
- packages/engine-content-api/src/mapper/select/handlers/FieldsVisitorFactory.ts
- packages/schema-definition/src/presets.ts
- packages/schema-utils/src/type-schema/settings.ts
- packages/schema/src/schema/settings.ts
Even if you use just a "date" format, the engine will respond with a iso datetime string. it is because node-pg automatically converts the date into `Date` object, which is later converted into a iso-string.
Now, you can set `content.shortDateResponse` to `true` to enable short response format.
Also, it will be a in default preset for 1.4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/488)
> date field: short response format

- packages/schema-definition/src/createSchema.ts
- packages/schema-definition/src/model/definition/context.ts
- packages/schema-definition/src/model/definition/extensions.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/FieldDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/ManyHasManyDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/ManyHasOneDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/OneHasOneDefinition.ts
- packages/schema-definition/src/model/definition/index.ts
- packages/schema-definition/src/model/definition/internal/SchemaBuilder.ts
- packages/schema-definition/src/strict.ts
- packages/schema-definition/tests/cases/unit/createSchema.test.ts
- packages/schema-definition/tests/cases/unit/extendEntity.test.ts
fixes #394
`createSchema` accepts `strict` option, which enables additional checks in the schema defintion, currently you may enable to require inverse side and explicit onDelete behaviour
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/490)
> schema definition strict mode

- packages/engine-tenant-api/src/model/service/PersonManager.ts
Attempting to execute the `changeMyProfile` mutation with an email that matches the one already associated with the user results in a validation error.
The existing code in `EmailValidator` currently verifies if the email is already in use, triggering an error in such scenarios.
This modification ensures that the mutation becomes idempotent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/510)
> fix(tenant-api): fix email validation upon profile change

- packages/engine-content-api/src/resolvers/GraphQlQueryAstFactory.ts
now, this failed:
```graphql
fragment MutationResult on MutationResult {
#...
}
mutation {
transaction {
createTag(data: {
name: "xxx"
}) {
... MutationResult
```
because MutationResult is an interface
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/508)
> fix: support interface fragments in graphql ast factory

- packages/engine-http/src/MasterContainer.ts
- packages/engine-http/src/application/application.ts
- packages/engine-http/src/config/configSchema.ts
- packages/engine-http/src/config/configTemplate.ts
- packages/logger/src/impl.ts
- packages/logger/src/proxy.ts
- packages/logger/src/types.ts
this PR adds following features:
- add `/health` endpoint on the primary http server, which returns 200 with `OK` body when the http is responding. this http endpoint does not require any authentication header or project group config
- add `CONTEMBER_HTTP_SUPPRESS_ACCESS_LOG` env option, which allows to lower the level of access logs from info to debug, either for all logs by setting this env to `1` or `true`, or by passing regex to suppress only some URLs
> http improvements: add /health endpoint, allow to suppress access log

- packages/engine-tenant-api/src/TenantContainer.ts
- packages/engine-tenant-api/src/model/authorization/PermissionActions.ts
- packages/engine-tenant-api/src/model/authorization/PermissionsFactory.ts
- packages/engine-tenant-api/src/resolvers/ResolverFactory.ts
- packages/engine-tenant-api/src/resolvers/query/PersonQueryResolver.ts
- packages/engine-tenant-api/src/resolvers/query/index.ts
- packages/engine-tenant-api/src/schema/index.ts
- packages/engine-tenant-api/src/schema/tenant.graphql.ts
- packages/engine-tenant-api/tests/cases/integration/mocked/personByIdQuery.test.ts
- packages/engine-tenant-api/tests/cases/integration/mocked/sql/getPersonByIdSql.ts
Implements this query on Tenant API
```graphql
query personById($id: String!) {
personById(id: $id) {
id
name
email
identity {
id
}
}
}
```
> feat(tenant-api): add query personById

- .github/workflows/build.yaml
AWS adds support for Aurora Postgres 16.1 so it will be great to test against PG 16.x
> chore: add postgres 16 to test matrix

- packages/engine-content-api/src/mapper/select/SelectBuilder.ts
- packages/engine-content-api/src/mapper/select/SelectHydrator.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/relationAcl.test.ts
This fixes an issue where ACL checks for relation visibility were batch processed across entire result sets, leading to incorrect data disclosure. Now, ACL conditions for relations are assessed individually for each row, ensuring the relation visibility aligns with the specific access permissions defined per entry. This change prevents the unintended exposure of relation values among entries sharing the same referenced entity but differing in accessibility conditions.
----
Example:
```ts
export const readerRole = c.createRole('reader')
@c.Allow(readerRole, {
read: ['title'],
})
@c.Allow(readerRole, {
when: { discloseAuthor: { eq: true } },
read: ['author'],
})
export class Article {
title = c.stringColumn().notNull()
author = c.manyHasOne(Author).notNull()
discloseAuthor = …
```
> Re-evaluate ACL relation predicates per-row in result set

- packages/cli/package.json
- packages/cli/src/utils/yaml.ts
- packages/cli/types/yawn-yaml/index.d.ts
- yarn.lock
Version `1.5.0` requires explicit import for CommonJS via `yawn-yaml/cjs`, version `1.5.1` brings support for just `yawn-yaml` for both CommonJS and ESM.
Project was rewritten to TypeScript and should be 1:1 but if we want to be sure and dont need any concerns we can upgrade just to `1.5.1`
> `yawn-yaml` version that support both CommonJS and ESM without explicit import

- packages/schema-migrations/src/modifications/columns/CreateColumnModification.ts
- packages/schema-migrations/src/modifications/columns/UpdateColumnDefinitionModification.ts
- packages/schema-migrations/src/modifications/columns/columnUtils.ts
- packages/schema-migrations/tests/cases/integration/createColumn.test.ts
- packages/schema-migrations/tests/cases/integration/updateColumnDefinition.test.ts
Enhance performance and flexibility by introducing the `valueMigrationStrategy` option in `createColumn` and `updateColumnDefinition` migrations. This option allows you to specify whether to employ a DML `update` statement or a DDL `using` statement when setting values with the `fillValue` or `copyValue` parameters.
Using the `using` strategy provides improved performance benefits during column addition or modification.  This efficiency gain is largely due to the strategy not recording changes in the event audit log.
When a migration involving `fillValue` is generated via a diff—triggered by setting a default value on a column—the system now automatically opts for the `using` strategy for optimal efficiency.
> migrations: allow to set column value with "using" 

- packages/database-migrations/src/runner.ts
- packages/engine-system-api/src/migrations/2024-06-28-150000-migrations-drop-sequence.ts
- packages/engine-system-api/src/migrations/runner.ts
- packages/engine-system-api/src/migrations/snapshot.ts
- packages/engine-system-api/src/model/commands/migrations/SaveMigrationCommand.ts
Sequences have some performance impacts, e.g. longer downtime during blue-green aws deployment.
> migration tables: do not use sequences

- packages/database/src/client/Connection.ts
- packages/database/src/client/Transaction.ts
- packages/database/src/client/errors.ts
- packages/database/tests/cases/unit/connection.test.ts
- packages/database/tests/cases/unit/createConnectionMockAlt.ts
- packages/database/tests/cases/unit/eventManager.test.ts
- packages/engine-content-api/src/mapper/ErrorUtils.ts
- packages/engine-content-api/src/mapper/EventManager.ts
- packages/engine-content-api/src/resolvers/MutationResolver.ts
- `commit` postgres may silently rollback, when previous error was ignored, so we check actual result of commit command
- execute Content API events serially, do not catch errors inside event handlers
- improve error handling during mutation commit
> Fix SQL-related errors affecting Actions

- packages/cli/src/lib/js/EvalExecutor.ts
To allow requires in bundled schema definition
> CLI: fix passing require in eval executor

- packages/engine-content-api/src/inputProcessing/UpdateInputVisitor.ts
- packages/engine-content-api/src/schema/mutations/UpdateEntityRelationInputFieldVisitor.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/update/manyHasManyOwning/connectOrCreate.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/update/oneHasMany/connectOrCreate.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-allowed.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-restricted-delete.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-basic.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-bug-66.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-custom-primary.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-has-many-reduction.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-new-builder.gql
`connectOrCreate` support was missing for many-has-many and one-has-many relations. For many-has-many, the behaviour is almost identical to the upsert with empty update
> feat(content-api): add connectOrCreate for has-many update

- packages/engine-http/src/content/ContentSchemaResolver.ts
- packages/engine-system-api/src/model/migrations/SchemaVersionBuilder.ts
This PR addresses a concurrency problem within the ContentSchemaResolver class, where multiple simultaneous invocations of getSchema could lead to redundant buildSchema executions. By ensuring that only one buildSchema operation runs at a time and reusing its result for concurrent requests, we enhance both performance and reliability.
Also, setImmediate is added to SchemaVersionBuilder to free event loop.
> (1.3 perf) schema builder concurrency

- packages/engine-content-api/src/mapper/select/handlers/FieldsVisitor.ts
- packages/playground/api/index.ts
- packages/playground/api/migrations/2024-10-08-134532-settings.json
- packages/schema-definition/src/model/definition/fieldDefinitions/ColumnDefinition.ts
- packages/schema-definition/src/presets.ts
- packages/schema-utils/src/type-schema/model.ts
- packages/schema-utils/src/type-schema/settings.ts
- packages/schema-utils/tests/cases/unit/modelSchema.test.ts
- packages/schema/src/schema/settings.ts
- packages/typesafe/src/index.ts
- this PR adds a shortcut for defining custom precision of timestamp
- also, user-defined columnType is fuzzy-validated
- add `content.fullDateTimeResponse` settings option, which will prevent JS Date object from stripping microseconds
> allow to set precision for dateTimeColumn + validate columnType

- packages/binding-legacy/src/core/TreeAugmenter.ts
- packages/playground/admin/app/components/navigation.tsx
- packages/playground/admin/app/pages/repeater.tsx
- packages/playground/api/migrations/2024-10-17-114124-repeater-rel.json
- packages/playground/api/model/Repeater.ts
This PR fixes a bug in the binding mechanism where newly persisted IDs were incorrectly mapped to existing binding states based on their order of reception. This approach could lead to mismatches and unintended overwrites, breaking data integrity and consistency within the application.
> binding: fix mapping has-many after persist to existing state

- packages/engine-tenant-api/src/model/service/idp/providers/OIDCHelpers.ts
- packages/engine-tenant-api/src/model/service/idp/providers/OIDCProvider.ts
- packages/engine-tenant-api/src/model/service/idp/providers/OIDCTypes.ts
Because BankID does not fully respect the OIDC specification about data retrieval, I need to be able to make additional request to their endpoint with their access token. I understand that this poses a vulnerability as the token should not leave contember but due to this contstraint I have no other choice.
> feat(tenant-api): optionally return full OIDC callback result

- packages/binding-legacy/src/core/operations/ListOperations.ts
An entity I'm trying to disconnect may not exist on every sibling state (e.g. due to dataview update).
> binding: disconnectEntity fix

- packages/engine-http/src/MasterContainer.ts
- packages/engine-http/src/content/ContentApiControllerFactory.ts
- packages/engine-http/src/content/ContentGraphQLContextFactory.ts
- packages/engine-http/src/content/ContentSchemaResolver.ts
- packages/engine-http/src/content/GraphQLSchemaContributor.ts
- packages/engine-http/src/content/GraphQlSchemaFactory.ts
- packages/engine-http/src/plugin/Plugin.ts
- packages/engine-http/src/project/ProjectContainer.ts
- packages/engine-http/src/system/ContentQueryExecutor.ts
- packages/engine-http/src/utils/memoizeObject.ts
- packages/engine-s3-plugin/src/S3SchemaContributor.ts
- packages/engine-s3-plugin/src/index.ts
- packages/engine-vimeo-plugin/src/VimeoSchemaContributor.ts
- packages/engine-vimeo-plugin/src/index.ts
This PR updates the caching mechanism for the GraphQL schema, expanding its scope to a global level. By enabling different projects with the same schema to share a single instance of the GraphQL schema object, it reduces cold start times and lowers memory usage.
Changes have been made to the schema extensions plugins to remove dependencies on project-specific configurations, ensuring compatibility across different projects. If some plugin depends on project config, it should return a cache key using getCacheKey in schema contributor.
> shared graphql schema

- packages/cli/src/dic.ts
- packages/cli/src/lib/env.ts
- packages/engine-system-api/src/SystemContainer.ts
- packages/schema-migrations/src/SchemaDiffer.ts
- packages/schema-migrations/src/modifications/acl/UpdateAclSchemaModification.ts
- packages/schema-migrations/src/modifications/validation/UpdateValidationSchemaModification.ts
This pull request introduces enhancements to the schema migration process by allowing the configuration of a maximum patch size for ACL and validation schema differences using CONTEMBER_MIGRATIONS_MAX_PATCH_SIZE  env for CLI.
> allow to set max patch size in migrations

- packages/cli-common/src/index.ts
- packages/cli-common/src/utils/findPackageRoot.ts
- packages/cli-common/src/utils/index.ts
- packages/cli/src/consts.ts
- packages/create/package.json
- packages/create/src/paths.ts
This pull request introduces several changes aimed at improving the package root resolution and simplifying the project structure. The key updates include the addition of a new utility function to find the package root and its integration into various parts of the codebase.
* [`packages/cli-common/src/utils/findPackageRoot.ts`](diffhunk://#diff-efc6e2e51abe9413fb3f66ef2888def16b9a2126b7a97e8ce7ed4c9d69548d8bR1-R20): Added a new utility function `findPackageRoot` to determine the root directory of a package by traversing up the directory tree until a `package.json` file is found.
* [`packages/cli/src/consts.ts`](diffhunk://#diff-73d0b43b3799173229739b56853b9a5db3d2fe2ee09c9127e8f20b45f929164cL1-R6): Replaced the existing logic for determining the package root with the new `findPackageRoot` …
> feat(cli-common): introduce findPackageRoot func

- .github/workflows/deploy-playground.yaml
This pull request includes a small change to the `.github/workflows/deploy-playground.yaml` file. The change updates the project name environment variable for the Contember admin from "playground2" to "playground".
* [`.github/workflows/deploy-playground.yaml`](diffhunk://#diff-9ada9d906b8fb7d822a6daa9dfea26ab32d9bf98efe5a90ab0b5740139a5f633L26-R26): Changed `VITE_CONTEMBER_ADMIN_PROJECT_NAME` from "playground2" to "playground".
> chore(playground): switch playground project name to playground instead of playground2

- .github/workflows/build.yaml
- .github/workflows/publish.yaml
- packages/engine-content-api/src/mapper/Mapper.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/update/acl/aclUpdate.test.ts
This pull request fixes an issue where read conditions in the ACL were not properly enforced during some nested mutations — primarily when using `connect`. Under certain circumstances, a user could reference an entity they were not allowed to read, simply by providing a valid unique identifier (e.g. slug or UUID).
Consider the following ACL and schema setup (simplified):
```ts
export const editor = c.createRole('editor')
@c.Allow(editor, {
read: true,
update: true,
})
export class Article {
category = c.manyHasOne(Category)
}
@c.Allow(editor, {
when: { isPublic: { eq: true } },
read: true,
})
export class Category {
isPublic = c.boolColumn().notNull()
slug = c.stringColumn().notNull().unique()
}
```
- An `editor` is allowed to read `Category` **only if** `isPublic` is `true`.
- However, …
> Correctly apply "read" predicates in nested mutations

- packages/react-devbar/src/index.css
Changed the `z-index` value of `devError` from `50` to `16777271` to ensure the element is properly layered above other elements.
> fix(react-devbar): move def error above all other elements

- docs/docs/reference/engine/schema/acl.md
- docs/package.json
- packages/engine-content-api/src/acl/Authorizator.ts
- packages/engine-content-api/src/acl/PermissionFactory.ts
- packages/engine-content-api/src/schema/MutationProvider.ts
- packages/engine-content-api/src/schema/QueryProvider.ts
- packages/engine-content-api/tests/cases/integration/graphQlSchema/graphQlSchemaBuilder.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-no-root-ops.gql
- packages/engine-content-api/tests/cases/unit/permissionMerger.test.ts
- packages/schema-definition/src/acl/builder/PermissionOverrider.ts
- packages/schema-definition/src/acl/definition/internal/AclFactory.ts
- packages/schema-definition/src/acl/definition/permissions.ts
- packages/schema-definition/tests/cases/unit/readAclDefinitions.test.ts
- packages/schema-migrations/src/modifications/utils/schemaUpdateUtils.ts
- packages/schema-utils/src/type-schema/acl.ts
- packages/schema/src/schema/acl.ts
This pull request introduces a new feature to handle operations that are disallowed at the root level in the ACL system. The changes include adding checks for root-level disallowed operations, updating permission merging logic, and adding tests for these new scenarios.
> content api: add basic support for excluding entities from root graphql operations

- e2e/cases/content/x-contember-ref.test.ts
- packages/engine-http/src/content/NotModifiedChecker.ts
- packages/engine-system-api/src/model/queries/events/LatestTransactionIdByStageQuery.ts
Currently Contember fails with internal server error if it recieves a request with `x-contember-ref`, but there is nothing in the `stage_transaction` table. 
The problem is there at least since v1.1. 
(I have not tested the fix.)
> fix(engine): handle empty x-contember-ref

- bun.lock
- packages/vite-plugin/src/index.ts
This pull request includes significant enhancements and refactoring to the `packages/vite-plugin/src/index.ts` file. The changes primarily focus on improving the configuration options for the Contember Vite plugin, adding detailed documentation, and enhancing the robustness of the plugin's functionalities.
* Added detailed JSDoc comments to the `ContemberOptions` type, providing clear descriptions for each option and their default values.
* Enhanced the destructuring of `options` in the `contember` function to include default values for `appPath`, `buildVersion`, and `disableMiddleware`.
* Introduced comprehensive documentation for the Contember Vite plugin, including a description of its features and an example usage.
* Improved the handling of the Contember DSN to include error handling …
> fix(vite-plugin): disable appending build version to html during development to disable outdated dialog

- bun.lock
- package.json
- packages/create/resources/templates/template-workspace/admin/package.json
- packages/create/resources/templates/template-workspace/package.json
- packages/playground/package.json
- packages/vite-plugin/package.json
This pull request includes several updates to the `vite` dependency across multiple package. The primary change is upgrading the `vite` version to `^6` in various `package.json` files. Also updated `vite-plugin` peer dependency to support versions `^5 || ^6`.
> chore: bump vite version

- e2e/cases/content/view-id.test.ts
- packages/engine-content-api/src/ExecutionContainer.ts
- packages/engine-content-api/src/mapper/select/handlers/FieldsVisitor.ts
- packages/engine-content-api/src/mapper/select/handlers/FieldsVisitorFactory.ts
- packages/engine-content-api/src/utils/viewComputedId.ts
- packages/schema-definition/src/model/definition/ViewDefinition.ts
- packages/schema-utils/src/type-schema/model.ts
- packages/schema/src/schema/model.ts
- **UUID Generation in Engine:** 
- Instead of generating UUIDs in the database, they can now be computed in the engine, reducing potential database performance overhead.
- When an entity’s primary key is `NULL`, a UUID is generated on the fly.
- **Computed ID Support:**
- Adds support for hash-based computed IDs by specifying `idSource` attributes in views.
- Uses a deterministic hash-based UUID approach to ensure stable IDs.
> views: generated primary key

- packages/react-ui-lib/src/editor/common/editor-block-toolbar.tsx
This pull request includes a small change to the `EditorBlockToolbar` component in the `packages/react-ui-lib` library. The change improves the layout of the toolbar by replacing the `space-x-2` class with `flex flex-wrap gap-2` for better spacing and wrapping of child elements.
* [`packages/react-ui-lib/src/editor/common/editor-block-toolbar.tsx`](diffhunk://#diff-f44b2c1fc8a39e8b197ef2f9613f5cee98232fed159c9b90755d7cfef9826e54L14-R14): Modified the `EditorBlockToolbar` component to use `flex flex-wrap gap-2` instead of `space-x-2` for improved layout and spacing.
> style(react-ui-lib): align block buttons in editor block toolbar

- bun.lock
- packages/create/package.json
- packages/create/src/commands/WorkspaceCreateCommand.ts
- packages/create/src/lib/FileSystem.ts
- packages/create/src/lib/TemplateInstaller.ts
This PR adds support for remote template sources in the create command by cloning templates from remote repositories. Key changes include:
- Integration of degit for cloning remote templates and managing temporary directories.
- Addition of a new "remove" method in the FileSystem abstraction.
- Enhancement of the CLI option for templates to accept remote sources.
> feat(create): add remote template source support

- packages/engine-http/src/content/ProjectMembershipResolver.ts
- packages/engine-tenant-api/src/model/authorization/MembershipMatcher.ts
- packages/engine-tenant-api/src/model/service/MembershipValidator.ts
- packages/schema-utils/src/type-schema/acl.ts
- packages/schema-utils/src/validation/MembershipResolver.ts
- packages/schema-utils/tests/cases/unit/membershipResolver.test.ts
- packages/schema/src/schema/acl.ts
- allow to override predefined variables in assume membership
- allow to simply set "true" instead of specifying per-level permissions for assume membership and some tenant-related operations
> improve assume membership

- docker-compose.override.dist.yaml
- docker-compose.yaml
- packages/cli/src/commands/actions/ActionsGetEventCommand.ts
- packages/cli/src/commands/actions/ActionsListFailedEventsCommand.ts
- packages/cli/src/commands/actions/ActionsListVariablesCommand.ts
- packages/cli/src/commands/actions/ActionsRetryEventCommand.ts
- packages/cli/src/commands/actions/ActionsSetVariablesCommand.ts
- packages/cli/src/commands/actions/ActionsStopEventCommand.ts
- packages/cli/src/dic.ts
- packages/cli/src/lib/actions/ActionsClient.ts
- packages/engine-actions/graphql.codegen.yml
- packages/engine-actions/src/authorization/ActionsAuthorizationActions.ts
- packages/engine-actions/src/dispatch/EventsRepository.ts
- packages/engine-actions/src/dispatch/ProjectDispatcher.ts
- packages/engine-actions/src/graphql/http/ActionsApiMiddlewareFactory.ts
- packages/engine-actions/src/graphql/resolvers/ActionsContext.ts
- packages/engine-actions/src/graphql/resolvers/ResolversFactory.ts
- packages/engine-actions/src/graphql/resolvers/mutation/RetryEventMutationResolver.ts
- packages/engine-actions/src/graphql/resolvers/mutation/StopEventMutationResolver.ts
- packages/engine-actions/src/graphql/resolvers/mutation/index.ts
- packages/engine-actions/src/graphql/resolvers/query/EventsQueryResolver.ts
- packages/engine-actions/src/graphql/schema/actions.graphql.ts
- packages/engine-actions/src/graphql/schema/index.ts
- packages/engine-actions/src/index.ts
- packages/engine-actions/src/model/EventByIdQuery.ts
- packages/engine-actions/src/triggers/TriggerPayloadPersister.ts
- packages/engine-actions/src/utils/notifyChannel.ts
- packages/playground/api/migrations/2025-03-31-145304-actions.json
- packages/playground/api/model/Actions.ts
- packages/playground/api/model/index.ts
This PR introduces several new CLI commands and backend GraphQL mutations to enhance observability and control over action events in Contember:
- `actions:list-variables` – List currently defined action variables.
- `actions:set-variables` – Set or update action variables with support for merge, set, or append-only modes.
- `actions:failed-events` – List failed action events, with optional JSON output.
- `actions:get-event` – Show details of a specific event.
- `actions:retry-event` – Manually requeue a failed event for processing.
- `actions:stop-event` – Mark an event as stopped to prevent further retries.
- Added `retryEvent` and `stopEvent` mutations to control event lifecycle via GraphQL.
- Fixed off-by-one error in retry attempt count.
- Introduced new event state: `stopped`.
- …
> Actions improvements
