contember/contember

- packages/engine-content-api/src/sql/insert/InsertBuilder.ts
- packages/engine-content-api/src/sql/update/UpdateBuilder.ts
…when abort happens in resolveData phase
> content api: insert & update builder: fix resolving aborted mutation 

- packages/engine-tenant-api/src/model/authorization/AclSchemaEvaluatorFactory.ts
- packages/engine-tenant-api/src/model/authorization/Identity.ts
- packages/engine-tenant-api/src/model/authorization/PermissionActions.ts
- packages/engine-tenant-api/src/model/authorization/PermissionsFactory.ts
- packages/engine-tenant-api/src/model/service/InviteManager.ts
- packages/engine-tenant-api/src/resolvers/ResolverFactory.ts
- packages/engine-tenant-api/src/resolvers/mutation/person/InviteMutationResolver.ts
- packages/engine-tenant-api/src/schema/index.ts
- packages/engine-tenant-api/src/schema/tenant.graphql.ts
- packages/engine-tenant-api/tests/cases/integration/db/invite.ts
- packages/engine-tenant-api/tests/cases/integration/db/unmanagedInvite.ts
- packages/engine-tenant-api/tests/cases/integration/mocked/gql/unmanagedInvite.ts
- packages/engine-tenant-api/tests/src/testTenantDb.ts
- packages/schema/src/schema/acl.ts
> tenant api: unmanaged invite

- packages/engine-api-tester/src/ContentApiTester.ts
- packages/engine-content-api/src/acl/StaticAuthorizator.ts
- packages/engine-content-api/src/acl/index.ts
- packages/engine-content-api/src/graphQLSchema/ContentSchemaFactory.ts
- packages/engine-content-api/src/graphQLSchema/GraphQlSchemaBuilderFactory.ts
- packages/engine-content-api/src/graphQLSchema/content-schema.graphql.ts
- packages/engine-content-api/src/graphQLSchema/content-schema.types.ts
- packages/engine-content-api/tests/cases/integration/graphQlSchema/graphQlSchemaBuilder.ts
- packages/engine-content-api/tests/src/test.ts
- packages/engine-http/src/content/GraphQlSchemaFactory.ts
> Content schema introspection updates

- packages/engine-tenant-api/src/model/service/SignInManager.ts
- packages/engine-tenant-api/src/schema/index.ts
- packages/engine-tenant-api/src/schema/tenant.graphql.ts
- packages/engine-tenant-api/tests/cases/integration/mocked/signInMutation.ts
Probably BREAKING CHANGE
Fixes contember/contember#117
> Fix typo OTP_REQURIED

- packages/database-tester/src/mocking.ts
- packages/engine-content-api/package.json
- packages/engine-content-api/src/bridges/system/ContentEventApplier.ts
- packages/engine-content-api/src/inputProcessing/MapperContainer.ts
- packages/engine-content-api/src/sql/JunctionTableManager.ts
- packages/engine-content-api/src/sql/Mapper.ts
- packages/engine-content-api/src/sql/delete/DeleteExecutor.ts
- packages/engine-content-api/src/sql/insert/InsertBuilder.ts
- packages/engine-content-api/src/sql/insert/InsertBuilderFactory.ts
- packages/engine-content-api/src/sql/select/JunctionFetcher.ts
- packages/engine-content-api/src/sql/select/Path.ts
- packages/engine-content-api/src/sql/select/SelectBuilder.ts
- packages/engine-content-api/src/sql/select/WhereBuilder.ts
- packages/engine-content-api/src/sql/update/UpdateBuilder.ts
- packages/engine-content-api/src/sql/update/UpdateBuilderFactory.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/misc/longAliasHash.test.ts
- yarn.lock
there are issues with farmhash cross platform compatibility. also, this should be much faster
> content api - long alias hashes: use alias counter

- packages/engine-content-api/src/acl/PredicateFactory.ts
- packages/engine-content-api/src/acl/PredicatesInjector.ts
- packages/engine-content-api/src/sql/select/handlers/FieldsVisitor.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/differentRowAndFieldPredicate.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/sameRowAndFieldPredicate.test.ts
> Content API ACL performance improvements

- packages/engine-content-api/src/resolvers/MutationResolver.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/upsert/basicUpsert.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/254)
> content api: fix upsert when no update is executed on main entity

- packages/cli-common/resources/templates/template-workspace/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/260)
> Template: Update deploy command

- packages/engine-content-api/src/acl/Authorizator.ts
- packages/engine-content-api/src/schema/entities/FieldTypeVisitor.ts
- packages/engine-content-api/tests/cases/integration/graphQlSchema/graphQlSchemaBuilder.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-predicate2.gql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/264)
> (1.0 backport) content api: fix column nullability

- packages/cli-common/resources/templates/template-workspace/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/262)
> Update Contember Admin to stable

- packages/database/src/builders/Compiler.ts
- packages/database/src/builders/QueryBuilder.ts
- packages/database/src/builders/SelectBuilder.ts
- packages/engine-content-api/src/mapper/select/OrderByBuilder.ts
- packages/engine-content-api/src/schema/OrderByTypeProvider.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/sorting/sortNulls.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-allowed.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-predicate.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-predicate2.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-restricted-create.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-restricted-delete.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-restricted-update.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-aliased-type.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-basic.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-bug-66.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-custom-primary.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-has-many-reduction.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-new-builder.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-view-entity.gql
- packages/schema/src/schema/input.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/265)
> Content API: nulls sorting behaviour

- packages/engine-content-api/src/extensions/paginatedHasMany/PaginatedHasManyFieldProviderVisitor.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/relations/oneHasMany.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/268)
> content api: fix aliases in paginated has-many

- packages/engine-tenant-api/src/model/commands/membership/variables/PatchProjectMembershipVariableValuesCommand.ts
- packages/engine-tenant-api/tests/cases/integration/mocked/sql/patchVariablesSql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/269)
> tenant api: fix sql for patching membership variables

- packages/database/src/builders/ConditionBuilder.ts
- packages/database/tests/cases/unit/queryBuilder.test.ts
- packages/engine-content-api/src/mapper/select/ConditionBuilder.ts
- packages/engine-content-api/src/mapper/select/WhereBuilder.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/271)
> Database: use ANY instead of IN for large inputs

- packages/engine-http/src/system/SystemApiMiddlewareFactory.ts
- packages/engine-http/src/system/SystemGraphQLContextFactory.ts
- packages/engine-http/src/system/SystemGraphQLHandlerFactory.ts
- packages/engine-server/src/project/ProjectSchemaResolver.ts
- packages/engine-tenant-api/src/model/type/Project.ts
- packages/engine-tenant-api/tests/src/testTenant.ts
- packages/engine-tenant-api/tests/src/testTenantDb.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/274)
> tenant api: cache project schema

- packages/engine-content-api/src/mapper/select/JoinVisitor.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/filter/manyHasManyOwnerRelation.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/276)
> Content API: limit length of aliases many-has-many

- packages/engine-system-api/src/model/migrations/ProjectMigrator.ts
- packages/schema-migrations/src/MigrationDescriber.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/278)
> schema migrations: do not validate individual modifications

- packages/database/src/client/Connection.ts
- packages/database/src/client/Pool.ts
- packages/engine-http/src/ProjectContainer.ts
- packages/engine-http/src/content/ContentApiMiddlewareFactory.ts
- packages/engine-http/src/system/SystemApiMiddlewareFactory.ts
- packages/engine-server/src/bootstrap/Initializer.ts
- packages/engine-server/src/project/ProjectContainerResolver.ts
- packages/engine-system-api/src/model/ProjectInitializer.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/275)
> Fix reaching connection limits in init phase

- packages/engine-content-api/src/input-validation/preValidation/InputPreValidator.ts
- packages/engine-content-api/src/mapper/select/ConditionBuilder.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/282)
> fix some null input handling

- packages/engine-content-api/src/schema/CustomTypesProvider.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/284)
> relax uuid pattern

- ee/engine-server-ee/src/prometheus/CustomMetric.ts
- ee/engine-server-ee/src/prometheus/dbMetrics.ts
- packages/database-tester/src/mocking.ts
- packages/database/src/client/Connection.ts
- packages/database/src/client/Pool.ts
- packages/database/tests/cases/unit/pool.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/280)
> add new db pool metrics

- packages/cli/Dockerfile
- packages/cli/build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/291)
> cli: fix generate doc

- packages/engine-content-api/tests/cases/unit/orderbyHelper.test.ts
- packages/schema-definition/src/model/builder/SchemaBuilderInternal.ts
- packages/schema-definition/src/model/definition/IndexDefinition.ts
- packages/schema-definition/src/model/definition/index.ts
- packages/schema-definition/src/model/definition/internal/SchemaBuilder.ts
- packages/schema-migrations/src/SchemaDiffer.ts
- packages/schema-migrations/src/modifications/ModificationHandlerFactory.ts
- packages/schema-migrations/src/modifications/entities/CreateEntityModification.ts
- packages/schema-migrations/src/modifications/entities/CreateViewModification.ts
- packages/schema-migrations/src/modifications/indexes/CreateIndexModification.ts
- packages/schema-migrations/src/modifications/indexes/RemoveIndexModification.ts
- packages/schema-migrations/src/modifications/indexes/index.ts
- packages/schema-migrations/src/utils/PartialEntity.ts
- packages/schema-migrations/tests/cases/integration/createAndDropIndex.test.ts
- packages/schema-migrations/tests/cases/integration/createEntity.test.ts
- packages/schema-migrations/tests/cases/integration/createManyHasMany.test.ts
- packages/schema-migrations/tests/cases/integration/createManyHasOne.test.ts
- packages/schema-migrations/tests/cases/integration/createOneHasMany.test.ts
- packages/schema-migrations/tests/cases/integration/createOneHasOne.test.ts
- packages/schema-migrations/tests/cases/integration/createView.test.ts
- packages/schema-migrations/tests/cases/integration/updateView.test.ts
- packages/schema-utils/src/model/NamingHelper.ts
- packages/schema-utils/src/type-schema/model.ts
- packages/schema/src/schema/model.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/292)
> Custom indexes

- packages/engine-content-api/src/input-validation/EntityRulesResolver.ts
- packages/engine-content-api/tests/cases/integration/graphQlDb/insert/insertSequence.test.ts
- packages/schema-utils/src/dataUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/296)
> Fix sequence

- packages/engine-http/src/content/ContentGraphQLContextFactory.ts
- packages/engine-server/tests/e2e/assume-identity.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/298)
> assume identity: permission fix + tests

- packages/engine-http/src/transfer/ContentSchemaTransferMappingFactory.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/300)
> fix(transfer-api): export many-has-many tables at the end

- packages/database-tester/src/mocking.ts
- packages/database/src/client/AcquiredConnection.ts
- packages/database/src/client/Client.ts
- packages/database/src/client/Connection.ts
- packages/database/src/client/Transaction.ts
- packages/database/src/utils/createDatabaseIfNotExists.ts
- packages/database/tests/cases/unit/createConnectionMockAlt.ts
- packages/engine-server/src/project/ProjectContainer.ts
- packages/engine-server/src/projectGroup/ProjectGroupContainer.ts
- packages/engine-system-api/src/model/ProjectInitializer.ts
- packages/engine-tenant-api/src/migrations/runner.ts
- packages/engine-tenant-api/tests/src/testTenantDb.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/299)
> database: remove query config

- packages/cli/src/commands/deploy/DeployCommand.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/302)
> CLI: abort deploy on migrations error

- packages/schema-utils/src/type-schema/model.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/301)
> fix schema back compatibility

- packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts
- packages/schema-definition/tests/unit/readAclDefinitions.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/305)
> validate fields in acl definition

- packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts
- packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts
- packages/engine-content-api/src/mapper/select/optimizer/helpers.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/filter/complexCondition.test.ts
- packages/engine-content-api/tests/cases/unit/conditionOptimizer.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/307)
> refactor(content-api): condition optimizer

- packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts
- packages/engine-content-api/src/acl/PredicateFactory.ts
- packages/engine-content-api/src/acl/PredicatesInjector.ts
- packages/engine-content-api/src/extensions/hasManyToHasOneReducer/HasManyToHasOneReducerExecutionHandler.ts
- packages/engine-content-api/src/extensions/paginatedHasMany/PaginatedHasManyCountVisitor.ts
- packages/engine-content-api/src/extensions/paginatedHasMany/PaginatedHasManyNodesVisitor.ts
- packages/engine-content-api/src/input-validation/ValidationDataSelector.ts
- packages/engine-content-api/src/mapper/Mapper.ts
- packages/engine-content-api/src/mapper/MapperContainer.ts
- packages/engine-content-api/src/mapper/select/RelationFetcher.ts
- packages/engine-content-api/src/mapper/select/WhereBuilder.ts
- packages/engine-content-api/src/mapper/select/handlers/FieldsVisitor.ts
- packages/engine-content-api/src/mapper/select/optimizer/ConditionOptimizer.ts
- packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts
- packages/engine-content-api/src/mapper/select/optimizer/helpers.ts
- packages/engine-content-api/src/resolvers/MutationResolver.ts
- packages/engine-content-api/src/resolvers/ReadHelpers.ts
- packages/engine-content-api/src/resolvers/ReadResolver.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/fieldRestrictedByLocale.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/predicateElimination.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/filter/complexCondition.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/filter/composedFilter.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/relations/manyHasManyInverse.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/relations/manyHasManyOwning.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/update/acl/aclUpdate.test.ts
- packages/engine-content-api/tests/cases/unit/conditionOptimizer.test.ts
- packages/engine-content-api/tests/cases/unit/predicatesFactory.test.ts
- packages/engine-content-api/tests/cases/unit/predicatesInjector.test.ts
- packages/engine-content-api/tests/cases/unit/whereOptimizer.test.ts
- packages/schema/src/schema/model.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/304)
> predicate elimination

- packages/engine-content-api/src/acl/PermissionFactory.ts
- packages/engine-content-api/src/utils/object.ts
- packages/engine-content-api/tests/cases/unit/permissionMerger.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/312)
> Fix permission merging

- packages/engine-content-api/src/mapper/select/optimizer/helpers.ts
- packages/engine-content-api/tests/cases/unit/conditionOptimizer.test.ts
- packages/engine-content-api/tests/cases/unit/whereOptimizer.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/316)
> fix condition optimizer: keep "never" in "or"

- packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts
- packages/engine-content-api/src/acl/PredicateFactory.ts
- packages/engine-content-api/src/acl/PredicatesInjector.ts
- packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts
- packages/engine-content-api/src/mapper/select/optimizer/WhereReplacer.ts
- packages/engine-content-api/src/mapper/select/optimizer/helpers.ts
- packages/engine-content-api/tests/cases/unit/predicatesInjector.test.ts
- packages/engine-content-api/tests/cases/unit/whereOptimizer.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/317)
> where predicate elimination

- packages/engine-http/src/transfer/ContentSchemaTransferMappingFactory.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/318)
> fix(transfer-api): do not transfer views

- packages/engine-http/src/transfer/ExportExecutor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/320)
> allow specify export target

- packages/engine-http/src/transfer/ExportExecutor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/322)
> fix(transfer-api): fix sequence value type

- packages/schema-migrations/src/modifications/columns/CreateColumnModification.ts
- packages/schema-migrations/src/modifications/columns/UpdateColumnDefinitionModification.ts
- packages/schema-migrations/src/modifications/entities/CreateEntityModification.ts
- packages/schema-migrations/src/modifications/utils/columnUtils.ts
- packages/schema-migrations/tests/cases/integration/createColumn.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/324)
> copyValue: explicit cast

- packages/engine-content-api/tests/cases/unit/whereBuilder.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/325)
> add where builder test

- packages/engine-content-api/src/mapper/select/WhereBuilder.ts
- packages/engine-content-api/tests/cases/unit/whereBuilder.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/326)
> fix isNull in has-many filters

- packages/engine-content-api/src/acl/EvaluatedPredicateReplacer.ts
- packages/engine-content-api/src/acl/PredicateFactory.ts
- packages/engine-content-api/src/acl/PredicatesInjector.ts
- packages/engine-content-api/src/extensions/hasManyToHasOneReducer/HasManyToHasOneReducerExecutionHandler.ts
- packages/engine-content-api/src/extensions/paginatedHasMany/PaginatedHasManyExecutionHandler.ts
- packages/engine-content-api/src/mapper/JunctionTableManager.ts
- packages/engine-content-api/src/mapper/Mapper.ts
- packages/engine-content-api/src/mapper/MapperContainer.ts
- packages/engine-content-api/src/mapper/delete/DeleteExecutor.ts
- packages/engine-content-api/src/mapper/insert/InsertBuilder.ts
- packages/engine-content-api/src/mapper/select/RelationFetcher.ts
- packages/engine-content-api/src/mapper/select/SelectBuilder.ts
- packages/engine-content-api/src/mapper/select/SelectExecutionHandler.ts
- packages/engine-content-api/src/mapper/select/SelectHydrator.ts
- packages/engine-content-api/src/mapper/select/WhereBuilder.ts
- packages/engine-content-api/src/mapper/select/handlers/FieldsVisitor.ts
- packages/engine-content-api/src/mapper/select/handlers/MetaHandler.ts
- packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts
- packages/engine-content-api/src/mapper/select/optimizer/WhereReplacer.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/differentRowAndFieldPredicate.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/fieldRestrictedByLocale.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/nestedPredicate.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/rowPredicateSubset.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/graphqlFeatures/alias.test.ts
- packages/engine-content-api/tests/cases/unit/predicatesInjector.test.ts
- packages/engine-content-api/tests/cases/unit/whereOptimizer.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/327)
> row predicates improvements

- packages/database/src/builders/LimitByGroupWrapper.ts
- packages/database/src/builders/SelectBuilder.ts
- packages/database/src/client/Pool.ts
- packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts
- packages/engine-content-api/src/mapper/select/optimizer/WhereReplacer.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/328)
> where optimizer performance improvements

- packages/engine-http/src/common/TimerMiddleware.ts
- packages/engine-http/src/content/ContentApiMiddlewareFactory.ts
- packages/engine-http/src/content/ContentGraphQLContextFactory.ts
- packages/engine-http/src/content/ContentQueryHandlerFactory.ts
- packages/engine-http/src/content/ProjectMembershipResolver.ts
- packages/engine-http/src/graphql/dbQueriesListener.ts
- packages/engine-http/src/system/SystemGraphQLHandlerFactory.ts
- packages/engine-http/src/transfer/ExportApiMiddlewareFactory.ts
- packages/engine-http/src/transfer/ImportExecutor.ts
- packages/engine-http/tests/cases/unit/projectMembershipResolver.test.ts
- packages/engine-server/src/MasterContainer.ts
- packages/schema-definition/src/acl/definition/internal/AclFactory.ts
- packages/schema-definition/src/acl/definition/roles.ts
- packages/schema-definition/tests/unit/readAclDefinitions.test.ts
- packages/schema-utils/src/schemaNormalizer.ts
- packages/schema-utils/src/type-schema/acl.ts
- packages/schema/src/schema/acl.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/330)
> allow to enable debug mode for a single request

- packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/334)
> Fix predicate references when referenced entity is always allowed

- packages/schema-definition/src/acl/definition/variables.ts
- packages/schema-utils/src/type-schema/acl.ts
- packages/schema-utils/src/validation/MembershipResolver.ts
- packages/schema-utils/tests/cases/unit/membershipResolver.test.ts
- packages/schema/src/schema/acl.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/333)
> ACL variable fallback

- packages/engine-server/package.json
- packages/engine-server/src/config/configSchema.ts
- packages/engine-server/tests/cases/configResolver.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/339)
> fix read replicas config resolving

- ee/engine-server-ee/src/prometheus/ProjectGroupContainerMetricsHook.ts
- ee/engine-server-ee/src/prometheus/dbMetrics.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/340)
> fix prom metrics for read replicas

- packages/cli/src/commands/migrations/MigrationAmendCommand.ts
- packages/schema-migrations/src/SchemaMigrator.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/344)
> CLI: migrations:amend command fix

- packages/engine-http/src/content/ContentApiMiddlewareFactory.ts
- packages/engine-http/src/content/NotModifiedChecker.ts
- packages/engine-system-api/src/model/queries/events/LatestTransactionIdByStageQuery.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/341)
> fix schema in LatestTransactionByIdQuery

- packages/schema-migrations/src/modifications/utils/schemaUpdateUtils.ts
- packages/schema-migrations/tests/cases/integration/removeField.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/342)
> migrations: drop unique / index when removing a field

- .github/workflows/build.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/346)
> fix ci config

- packages/schema-utils/src/validation/ModelValidator.ts
- packages/schema-utils/tests/cases/unit/modelValidator.test.ts
fixes #255
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/348)
> validator: check "Meta" suffix

- packages/benchmark/src/projects/app/api/src/model.ts
- packages/engine-api-tester/src/testWithDb.ts
- packages/engine-content-api/src/mapper/MapperContainer.ts
- packages/engine-content-api/src/mapper/select/Path.ts
- packages/engine-content-api/src/mapper/select/WhereBuilder.ts
- packages/engine-content-api/tests/cases/bugs/bug102.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/filter/manyHasManyOwnerRelation.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/filter/oneHasManyRelation.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/unique/oneHasManyUnique.test.ts
- packages/engine-content-api/tests/cases/unit/whereBuilder.test.ts
- packages/engine-tenant-api/tests/src/testTenant.ts
- packages/engine-tenant-api/tests/src/testTenantDb.ts
- packages/schema-definition/src/createSchema.ts
- packages/schema-migrations/src/SchemaDiffer.ts
- packages/schema-migrations/src/modifications/ModificationHandlerFactory.ts
- packages/schema-migrations/src/modifications/settings/UpdateSettingsModification.ts
- packages/schema-migrations/src/modifications/settings/index.ts
- packages/schema-migrations/tests/src/tests.ts
- packages/schema-utils/src/index.ts
- packages/schema-utils/src/type-schema/index.ts
- packages/schema-utils/src/type-schema/settings.ts
- packages/schema/src/index.ts
- packages/schema/src/schema/settings.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/337)
> has-many filters: always use exists

- packages/schema-definition/src/model/definition/ViewDefinition.ts
- packages/schema-definition/src/model/definition/extensions.ts
- packages/schema-definition/src/model/definition/internal/SchemaBuilder.ts
- packages/schema-definition/tests/unit/extendEntity.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/357)
> schema definition: improve entity extensibility

- packages/schema-definition/src/acl/definition/internal/EntityPredicateResolver.ts
- packages/schema-definition/tests/unit/readAclDefinitions.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/350)
> fix predicate name collision

- packages/engine-api-tester/src/testWithDb.ts
- packages/engine-content-api/src/mapper/delete/DeleteExecutor.ts
- packages/engine-content-api/src/resolvers/MutationResolver.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/delete/aclDelete.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/delete/additionalDeleteFilter.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/delete/cascadeDelete.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/delete/deleteById.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/delete/orphanRemoval.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/delete/setNullOnDelete.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/update/manyHasManyInverse/delete.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/update/manyHasManyOwning/delete.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/update/manyHasOne/delete.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/update/oneHasMany/combination.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/update/oneHasMany/delete.test.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/update/oneHasOneInverse/delete.test.ts
- packages/engine-content-api/tests/src/testGraphql.ts
- packages/logger/src/proxy.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/349)
> Fix deferring FKs in delete executor

- packages/cli/src/commands/migrations/MigrationDiffCommand.ts
- packages/cli/src/commands/migrations/MigrationValidationHelper.ts
- packages/cli/src/utils/schema.ts
- packages/engine-system-api/src/model/migrations/ProjectMigrator.ts
- packages/engine-system-api/src/schema/system.graphql.ts
- packages/engine-system-api/src/schema/types.ts
- packages/schema-migrations/src/Migration.ts
- packages/schema-migrations/src/MigrationCreator.ts
- packages/schema-migrations/src/MigrationsResolver.ts
- packages/schema-migrations/src/SchemaDiffer.ts
- packages/schema-migrations/tests/src/tests.ts
- packages/schema-utils/src/validation/AclValidator.ts
- packages/schema-utils/src/validation/ModelValidator.ts
- packages/schema-utils/src/validation/SchemaValidator.ts
- packages/schema-utils/src/validation/ValidationValidator.ts
- packages/schema-utils/src/validation/errors.ts
- packages/schema-utils/tests/cases/unit/modelValidator.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/358)
> validator: allow to skip errors

- packages/database/src/client/Connection.ts
- packages/database/src/client/EventManager.ts
- packages/database/src/client/Pool.ts
- packages/database/src/client/errors.ts
- packages/database/tests/cases/unit/pool.test.ts
- packages/engine-server/src/config/configSchema.ts
- packages/engine-server/src/config/configTemplate.ts
- packages/engine-system-api/src/model/ProjectInitializer.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/354)
> database: handle "timeout expired" errors

- .github/workflows/build.yaml
- .github/workflows/publish-canary.yaml
- .github/workflows/publish.yaml
- docker-compose.yaml
- packages/cli/Dockerfile
- packages/cli/package.json
- packages/cli/src/commands/deploy/DeployCommand.ts
- packages/cli/src/commands/transfer/ExportCommand.ts
- packages/cli/src/commands/transfer/ImportCommand.ts
- packages/cli/src/commands/transfer/TransferCommand.ts
- packages/cli/src/commands/transfer/index.ts
- packages/cli/src/commands/transfer/utils.ts
- packages/cli/src/run.ts
- packages/cli/src/utils/dsn.ts
- packages/cli/src/utils/stdio.ts
- packages/cli/src/utils/stream.ts
- scripts/docker/server-alpine.dockerfile
- scripts/docker/server-debian.dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/356)
> CLI: transfer commands

- packages/engine-content-api/src/acl/PredicatesInjector.ts
- packages/engine-content-api/src/mapper/select/ConditionBuilder.ts
- packages/engine-content-api/src/mapper/select/WhereBuilder.ts
- packages/engine-content-api/src/mapper/select/optimizer/helpers.ts
- packages/engine-content-api/tests/cases/unit/predicatesInjector.test.ts
- packages/engine-content-api/tests/cases/unit/whereBuilder.test.ts
- packages/schema/src/schema/input.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/361)
> fix(content-api): handle possible nulls in a filter

- packages/engine-tenant-api/src/model/queries/membership/ProjectMembersQuery.ts
- packages/engine-tenant-api/src/model/service/ProjectMemberManager.ts
- packages/engine-tenant-api/src/resolvers/types/ProjectTypeResolver.ts
- packages/engine-tenant-api/src/schema/index.ts
- packages/engine-tenant-api/src/schema/tenant.graphql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/351)
> tenant api improvements

- packages/engine-http/src/content/ProjectMembershipResolver.ts
- packages/engine-http/tests/cases/unit/projectMembershipResolver.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/364)
> feat(content-api): allow to send assumeMembership in a body

- packages/engine-http/src/content/ProjectMembershipResolver.ts
- packages/engine-http/tests/cases/unit/projectMembershipResolver.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/365)
> 1.2 backport: assume membership body

- packages/engine-content-api/src/acl/VariableInjector.ts
- packages/schema-utils/src/acl/PredicateDefinitionProcessor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/369)
> perf(content-api): cache result in VariableInjector

- ee/engine-server-ee/src/http/CollectHttpMetricsMiddelware.ts
- ee/engine-server-ee/src/prometheus/dbMetrics.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/368)
> fix prom metrics

- packages/engine-content-api/src/mapper/Mapper.ts
- packages/engine-content-api/src/mapper/select/RelationFetcher.ts
- packages/engine-content-api/src/mapper/select/optimizer/WhereOptimizer.ts
- packages/engine-content-api/src/mapper/select/optimizer/WhereReplacer.ts
- packages/engine-content-api/tests/cases/unit/whereOptimizer.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/372)
> where optimizer improvements

- packages/engine-s3-plugin/src/S3Service.ts
- packages/engine-s3-plugin/tests/cases/signRequest.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/377)
> fix generating s3 read urls

- packages/engine-s3-plugin/src/S3Service.ts
- packages/engine-s3-plugin/tests/cases/signRequest.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/378)
> (1.2 backport) fix generating s3 read urls 

- packages/schema-utils/src/definition-generator/TsDefinitionGenerator.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/412)
> ts generator decorators fix

- packages/schema-definition/tests/unit/readActions.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/413)
> fix tests in schema definition

- packages/schema-utils/package.json
- packages/schema-utils/src/model/NamingHelper.ts
- scripts/lint/module-import-linter.ts
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/414)
> schema utils: browser compat

- packages/cli-common/resources/templates/template-workspace/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/418)
> fix(template): remove cli container after use

- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/isNullAcl.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/427)
> [backport 1.2] tests(content-api): add test for disproven regression

- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/acl/isNullAcl.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/426)
> tests(content-api): add test for disproven regression

- packages/schema-migrations/src/SchemaDiffer.ts
- packages/schema-utils/src/index.ts
- packages/schema-utils/src/utils/deepCompare.ts
- packages/schema-utils/tests/cases/unit/deepCompare.test.ts
bug introduced in #424
validation failed in some cases, when there was an index order mismatch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/442)
> fix validating order of indexes and unique

- packages/engine-content-api/src/mapper/delete/DeleteExecutor.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/delete/restrictOnDelete.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/447)
> ignore view entities in delete executor dependencies

- packages/cli/src/commands/project/ProjectPrintSchemaCommand.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/446)
> CLI: add --normalize option to a print schema command

- packages/cli/src/commands/migrations/MigrationValidationHelper.ts
- packages/engine-system-api/src/model/migrations/ProjectMigrator.ts
- packages/schema-utils/src/validation/SchemaValidator.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/452)
> schema validation: add skipUntil to skippedErrors

- packages/engine-tenant-api/src/migrations/2023-01-20-135500-person-email-normalize.ts
- packages/engine-tenant-api/src/migrations/runner.ts
- packages/engine-tenant-api/src/model/commands/person/CreatePersonCommand.ts
- packages/engine-tenant-api/src/model/queries/person/PersonQuery.ts
- packages/engine-tenant-api/src/model/queries/person/types.ts
- packages/engine-tenant-api/src/model/utils/email.ts
- packages/engine-tenant-api/tests/cases/integration/mocked/signInMutation.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/363)
> tenant api: email normalization

- packages/typesafe/src/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/458)
> fix(typesafe): pass the path in discriminated union

- ee/engine-actions/package.json
- ee/engine-actions/src/authorization/ActionsAuthorizationActions.ts
- ee/engine-actions/src/authorization/ActionsPermissionsFactory.ts
- ee/engine-actions/src/authorization/Identity.ts
- ee/engine-actions/src/authorization/index.ts
- ee/engine-actions/src/dispatch/EventsRepository.ts
- ee/engine-actions/src/dispatch/WebhookFetcher.ts
- ee/engine-actions/src/dispatch/WebhookTargetHandler.ts
- ee/engine-actions/src/dispatch/types.ts
- ee/engine-actions/src/graphql/http/ActionsApiMiddlewareFactory.ts
- ee/engine-actions/src/graphql/http/ActionsContextResolver.ts
- ee/engine-actions/src/graphql/resolvers/ActionsContext.ts
- ee/engine-actions/src/graphql/resolvers/mutation/ProcessBatchMutationResolver.ts
- ee/engine-actions/src/graphql/resolvers/mutation/SetVariablesMutationResolver.ts
- ee/engine-actions/src/graphql/resolvers/query/EventsQueryResolver.ts
- ee/engine-actions/src/graphql/resolvers/query/VariablesQueryResolver.ts
- ee/engine-actions/src/index.ts
- ee/engine-actions/src/model/types.ts
- ee/engine-actions/src/triggers/Payload.ts
- ee/engine-actions/src/triggers/TriggerPayloadBuilder.ts
- ee/engine-actions/src/triggers/TriggerPayloadPersister.ts
- ee/engine-actions/src/tsconfig.json
- ee/engine-actions/tests/cases/integration/triggers.rootWatch.test.ts
- ee/engine-actions/tests/cases/unit/webhookHandler.test.ts
- packages/schema-definition/src/actions/definition/internal/ActionsFactory.ts
- packages/schema-definition/src/actions/definition/triggers.ts
- packages/schema-definition/tests/cases/unit/readActions.test.ts
- yarn.lock
Few fixes and improvements regarding actions:
- fixed event payload when watched entity is deleted #428 
- changed default batch size to 1, because it is easier to understand and process
- add meta info to event, like timestamp of the event, event id or transaction id
- add priority to public actions api
- webhook name in advanced webhook configuration is now optional
- allow "deployer" to setup actions variables
- partial success processing
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/443)
> actions improvements and fixes

- packages/schema-migrations/src/modifications/columns/columnUtils.ts
- packages/schema-migrations/tests/cases/integration/createColumn.test.ts
- packages/schema-migrations/tests/cases/integration/updateColumnDefinition.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/461)
> migrations: fix firing constraint triggers

- packages/engine-http/src/application/application.ts
- packages/engine-http/src/content/ContentApiControllerFactory.ts
- packages/engine-http/src/system/SystemApiMiddlewareFactory.ts
- packages/engine-http/src/tenant/TenantApiMiddlewareFactory.ts
- packages/engine-http/src/utils/sentry.ts
- packages/logger/src/levels.ts
- packages/logger/src/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/463)
> various logging fixes

- packages/engine-http/src/graphql/execution.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/465)
> [backport] #464 to 1.2

- packages/cli/src/utils/project/loadSchema.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/467)
> feat(cli): support sql file import in model

- packages/engine-http/src/transfer/ExportApiControllerFactory.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/473)
> fix response compress in export endpoint

- packages/cli/src/commands/transfer/ExportCommand.ts
- packages/cli/src/commands/transfer/ImportCommand.ts
- packages/cli/src/commands/transfer/TransferCommand.ts
- packages/cli/src/utils/stdio.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/474)
> fix(cli): handle undefined clearLine in data import / export

- packages/engine-tenant-api/src/model/service/idp/providers/AppleProvider.ts
- packages/engine-tenant-api/src/model/service/idp/providers/FacebookProvider.ts
- packages/engine-tenant-api/src/model/service/idp/providers/OIDCProvider.ts
- packages/engine-tenant-api/src/model/service/idp/providers/OIDCTypes.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/482)
> Tenant: support additional AZP in OIDC client

- packages/cli-common/src/utils/Workspace.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/483)
> feat(cli): CLI works in single-project mode, when there is no project mapping

- packages/engine-tenant-api/src/model/queries/membership/ProjectMembersQuery.ts
- packages/engine-tenant-api/src/resolvers/types/ProjectTypeResolver.ts
- packages/engine-tenant-api/src/schema/index.ts
- packages/engine-tenant-api/src/schema/tenant.graphql.ts
- packages/engine-tenant-api/tests/cases/integration/mocked/listProjectMembersQuery.test.ts
Allow to filter project members by array of identityId and personId. Also, allow an array in "email" filter
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/485)
> tenant api: improve members filter

- packages/engine-tenant-api/src/model/service/InviteManager.ts
- packages/engine-tenant-api/src/model/service/SignUpManager.ts
- packages/engine-tenant-api/src/model/utils/email.ts
- packages/engine-tenant-api/src/schema/index.ts
- packages/engine-tenant-api/src/schema/tenant.graphql.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/487)
> validate email format in signUp and invite mutations

- ee/engine-actions/src/graphql/http/ActionsWebsocketControllerFactory.ts
When a WebSocket client issues a `startWorker` command followed immediately by a `stopAllWorkers` command, there's a chance that the worker may not have been fully started yet. This can result in the worker turning into a "zombie" worker that is not properly managed. To address this, we ensure that the worker is synchronously added to the `workers` list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/492)
> actions: fix worker termination

- .github/workflows/build.yaml
This PR add PostgreSQL 15 to test matrix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/495)
> chore(ci): add PostgreSQL 15 to test matrix

- packages/cli/src/commands/deploy/DeployCommand.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/497)
> cli: fix deploy command message

- packages/engine-content-api/src/mapper/select/RelationFetcher.ts
- packages/engine-content-api/tests/cases/integration/graphQlRequests/query/relations/manyHasManyOwning.test.ts
This PR addresses performance issues related to the use of the SQL IN operator in many-has-many relations when dealing with large data sets. Previously, we adopted the value = ANY(?::uuid[]) syntax in certain parts, resulting in notable performance improvements.
This change extends this optimization to additional areas involving many-has-many relations, aiming to enhance query performance, and prevent hitting the PostgreSQL bindings limit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/502)
> Content API: Optimize / fix SQL Queries in Many-Has-Many Relations

- packages/engine-content-api/src/schema/GraphQlSchemaBuilder.ts
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-allowed.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-create-only.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-restricted-create.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-restricted-delete.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl-restricted-update.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-acl.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-aliased-type.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-basic.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-bug-66.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-custom-primary.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-has-many-reduction.gql
- packages/engine-content-api/tests/cases/integration/graphQlSchema/schema-new-builder.gql
- packages/engine-http/src/content/GraphQlSchemaFactory.ts
avoid QueryPortal type, use Query as it was before
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/504)
> schema merging refactor for better BC

- docker-compose.override.dist.yaml
- ee/engine-actions/src/dispatch/DispatchWorkerSupervisor.ts
- ee/engine-actions/src/graphql/http/ActionsApiMiddlewareFactory.ts
- ee/engine-server-ee/src/prometheus/ProjectGroupContainerMetricsHook.ts
- packages/engine-api-tester/src/testWithDb.ts
- packages/engine-http/src/common/Authorizator.ts
- packages/engine-http/src/config/configTemplate.ts
- packages/engine-http/src/content/ContentApiControllerFactory.ts
- packages/engine-http/src/project/ProjectContainer.ts
- packages/engine-http/src/project/ProjectSchemaResolver.ts
- packages/engine-http/src/projectGroup/ProjectGroupContainer.ts
- packages/engine-http/src/system/SystemGraphQLContextFactory.ts
- packages/engine-http/src/transfer/ExportApiControllerFactory.ts
- packages/engine-http/src/transfer/ExportExecutor.ts
- packages/engine-http/src/transfer/ImportExecutor.ts
- packages/engine-http/tests/cases/unit/configResolver.test.ts
- packages/engine-system-api/src/bin/runMigrations.ts
- packages/engine-system-api/src/model/ProjectInitializer.ts
- packages/engine-system-api/src/model/database/DatabaseContext.ts
- packages/engine-tenant-api/src/TenantContainer.ts
- packages/engine-tenant-api/src/model/commands/apiKey/ApiKeyHelper.ts
- packages/engine-tenant-api/src/model/commands/apiKey/ProlongApiKeyCommand.ts
- packages/engine-tenant-api/src/model/service/apiKey/ApiKeyManager.ts
- packages/engine-tenant-api/src/model/utils/DatabaseContext.ts
- packages/engine-tenant-api/tests/src/testTenant.ts
- packages/engine-tenant-api/tests/src/testTenantDb.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/491)
> support read replicas in tenant and system

- packages/engine-tenant-api/src/TenantContainer.ts
- packages/engine-tenant-api/src/migrations/2023-09-01-165000-idp-return-config.ts
- packages/engine-tenant-api/src/migrations/runner.ts
- packages/engine-tenant-api/src/migrations/snapshot.ts
- packages/engine-tenant-api/src/model/commands/idp/CreateIdpCommand.ts
- packages/engine-tenant-api/src/model/commands/idp/UpdateIdpCommand.ts
- packages/engine-tenant-api/src/model/queries/idp/helpers.ts
- packages/engine-tenant-api/src/model/queries/idp/types.ts
- packages/engine-tenant-api/src/model/service/IDPSignInManager.ts
- packages/engine-tenant-api/src/model/service/idp/IDPHandlerRegistry.ts
- packages/engine-tenant-api/src/model/service/idp/IDPManager.ts
- packages/engine-tenant-api/src/model/service/idp/IdentityProviderHandler.ts
- packages/engine-tenant-api/src/model/service/idp/providers/AppleProvider.ts
- packages/engine-tenant-api/src/model/service/idp/providers/FacebookProvider.ts
- packages/engine-tenant-api/src/model/service/idp/providers/OIDCProvider.ts
- packages/engine-tenant-api/src/model/type/IdentityProvider.ts
- packages/engine-tenant-api/src/resolvers/mutation/idp/AddIDPMutationResolver.ts
- packages/engine-tenant-api/src/resolvers/mutation/idp/UpdateIDPMutationResolver.ts
- packages/engine-tenant-api/src/resolvers/query/IDPQueryResolver.ts
- packages/engine-tenant-api/src/schema/index.ts
- packages/engine-tenant-api/src/schema/tenant.graphql.ts
- packages/engine-tenant-api/tests/cases/integration/mocked/signInIdpMutation.test.ts
- packages/engine-tenant-api/tests/cases/integration/mocked/sql/getIdpBySlugSql.ts
- hide private configuration parameters when listing IdPs
- allow to merge with current config when calling updateIDP
- allow initSignInIDP to return current IdP configuration (must be enabled for the IdP)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/489)
> idp configuration improvements

- packages/engine-http/src/application/application.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/506)
> fix prom metrics labels

- packages/engine-http/src/config/configTemplate.ts
- packages/engine-http/src/config/projectConfigResolver.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/511)
> allow to change default stage slug

- packages/schema-migrations/src/SchemaDiffer.ts
- packages/schema-migrations/src/modifications/ModificationHandlerFactory.ts
- packages/schema-migrations/src/modifications/relations/ConvertOneHasManyToOneHasOneRelationModification.ts
- packages/schema-migrations/src/modifications/relations/ConvertOneToManyRelationModification.ts
- packages/schema-migrations/tests/cases/integration/convertManyHasOneToOneHasOneRelation.test.ts
- packages/schema-migrations/tests/cases/integration/convertOneToManyRelation.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/509)
> schema migrations: add migration for converting 1:N to 1:1 relation

- packages/engine-system-api/src/model/queries/migrations/ExecutedMigrationsQueryHelper.ts
> fix system migrations in 1.4

- packages/schema-utils/src/definition-generator/AclDefinitionCodeGenerator.ts
- packages/schema-utils/src/definition-generator/DefinitionCodeGenerator.ts
- packages/schema-utils/tests/cases/unit/__snapshots__/laxSchemaConverter.test.ts.snap
- packages/schema-utils/tests/cases/unit/schemas/acl.ts
- packages/schema-utils/tests/cases/unit/schemas/basic.ts
- packages/schema-utils/tests/cases/unit/schemas/enum.ts
- packages/schema-utils/tests/cases/unit/schemas/relations.ts
- packages/schema-utils/tests/cases/unit/schemas/unique.ts
- **feat(schema-utils): use c import from schema-definition instead of SchemaDefinition and AclDefinition**
- **test(schema-utils): update tests for definition code generator**
> use c instead of def and acl

- packages/schema-definition/src/index.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/ColumnDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/FieldDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/ManyHasManyDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/ManyHasManyInverseDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/ManyHasOneDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/OneHasManyDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/OneHasOneDefinition.ts
- packages/schema-definition/src/model/definition/fieldDefinitions/OneHasOneInverseDefinition.ts
- packages/schema-definition/src/model/definition/index.ts
- packages/schema-definition/src/model/definition/types.ts
export and refactor some types to avoid this error
> Fix ts2742 related errors in schema definition package

- packages/schema-migrations/src/modifications/entities/RemoveEntityModification.ts
- packages/schema-migrations/tests/cases/integration/removeEntity.test.ts
when an entity with many has many relation is removed
fixes #565
> migrations fix: remove junction table

- build/api/react-ui-lib.api.md
- packages/playground/admin/app/components/navigation.tsx
- packages/playground/admin/app/pages/ui/dialog.tsx
- packages/react-ui-lib/src/ui/alert-dialog.tsx
- packages/react-ui-lib/src/ui/dialog.tsx
- packages/react-ui-lib/src/ui/dropdown.tsx
- packages/react-ui-lib/src/ui/popover.tsx
- packages/react-ui-lib/src/ui/select.tsx
- packages/react-ui-lib/src/ui/sheet.tsx
- packages/react-ui-lib/src/utils/createComponentOpenHooks.tsx
introduce hooks like useDialogOpenState for controlling state of openable components
> dialogs: add hooks for controlling open state

- packages/react-ui-lib/src/datagrid/column-header.tsx
Make datagrid column header text size consistent.
> style: change font size for default header

- packages/react-ui-lib/src/block-repeater/block-repeater.tsx
- packages/react-ui-lib/src/datagrid/grid.tsx
- packages/react-ui-lib/src/layout/layout.tsx
- packages/react-ui-lib/src/repeater/repeater.tsx
> feat(react-ui-lib): remove borders from repeater

- build/api/react-devbar.api.md
- packages/react-devbar/src/index.css
- packages/react-devbar/src/ui/DevBar/DevBar.tsx
- packages/react-devbar/src/ui/DevError/DevErrorList.tsx
- scripts/ae-update/ae.dockerfile
This pull request includes several changes to the `react-devbar` package, focusing on refactoring, style improvements, and functional updates. The most important changes are grouped into API adjustments, CSS updates, and functional improvements.
* [`build/api/react-devbar.api.md`](diffhunk://#diff-a0266c025c1ebbb9654fdb51882538d7e5f5a8dcdf71a014c6d9282d47a23e14L18-R18): Updated `DevBar` and `DevPanel` to use `PropsWithChildren` and `DevPanelProps` respectively, and removed the `brand` prop from `DevBar`. [[1]](diffhunk://#diff-a0266c025c1ebbb9654fdb51882538d7e5f5a8dcdf71a014c6d9282d47a23e14L18-R18) [[2]](diffhunk://#diff-a0266c025c1ebbb9654fdb51882538d7e5f5a8dcdf71a014c6d9282d47a23e14R65-R68)
* [`packages/react-devbar/src/index.css`](diffhunk://#diff-556f4de2180ea63a4030e8ef5df299bf6e0e053 …
> feat(react-devbar): update react devbar styling

- docker-compose.yaml
- e2e/cases/actions/triggers.cascadeDelete.test.ts
- e2e/src/tester.ts
- packages/engine-actions/src/triggers/TriggerPayloadBuilder.ts
pre-fetched selection might exists on any event, not just a first one
> actions: events payload fix

- build/api/react-dataview.api.md
- packages/react-dataview/src/components/DataViewReloadTrigger.tsx
- packages/react-dataview/src/internal/hooks/useDataViewPaging.ts
- packages/react-dataview/src/internal/hooks/useDataViewTotalCount.ts
- packages/react-dataview/src/types/paging.ts
- add refreshTotalCount method to paging methods
- trigger total count refresh in DataViewReloaTrigger
> dataview: refresh total count

- packages/react-ui-lib/src/select/select.tsx
- packages/react-ui-lib/src/select/ui.tsx
Fix the `Select` to allow user click on chevron icon and don't hide select value behind action buttons.
> fix(react-ui-lib): move select action buttons to select body make chevron icon clickable

- start.sh
Use Bun Instead of Yarn in start.sh
> Use Bun Instead of Yarn in start.sh

- packages/cli/src/lib/migrations/MigrationExecutionFacade.ts
- packages/migrations-client/src/MigrationExecuteHelper.ts
- packages/migrations-client/src/MigrationFile.ts
- fix passing migrations factory args
- add additional args passed to migrations factory allowing you to build a schema
> migrations factory args

- packages/cli/src/commands/transfer/ExportCommand.ts
- packages/cli/src/commands/transfer/ImportCommand.ts
- packages/cli/src/commands/transfer/TransferCommand.ts
- packages/cli/src/lib/transfer/DataTransferClient.ts
This PR replaces low-level `http`/`https` streams with the `fetch` API to resolve stability issues (notably with Bun runtime).
- More stable behavior, especially with Bun
- Simpler and cleaner request/response handling
- Unified stream processing via `Readable.fromWeb` / `toWeb`
- Gzipped responses are now auto-decompressed by `fetch`, so re-compression is needed if output should be gzipped
- Slight overhead due to stream conversion (web ↔ Node.js)
> CLI: use fetch instead of request for data transfer
